version: "3"

tasks:
  install-melos:
    cmds:
      - dart pub global activate melos

  install-mason:
    cmds:
      - dart pub global activate mason_cli

  create-feature:
    cmds:
      - mason make feature
      - melos bootstrap

  create-library:
    cmds:
      - mason make library
      - melos bootstrap

  graph-dependencies:
    cmds:
      - melos list --all --graph 

  gviz-dependencies:
    cmds:
      - melos list --all --gviz 