version: "3"

tasks:
  install-melos:
    cmds:
      - dart pub global activate melos

  install-mason:
    cmds:
      - dart pub global activate mason_cli

  create-feature:
    cmds:
      - mason make feature
      - melos bootstrap

  create-library:
    cmds:
      - mason make library
      - melos bootstrap

  graph:
    cmds:
      - melos list --all --graph

  gviz:
    cmds:
      - echo https://dreampuf.github.io/GraphvizOnline/#$(melos list --all --gviz | python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.stdin.read()))")
