version: "3"

tasks:
  install-melos:
    cmds:
      - dart pub global activate melos

  install-mason:
    cmds:
      - dart pub global activate mason_cli

  create-feature:
    cmds:
      - mason make feature
      - melos bootstrap

  create-library:
    cmds:
      - mason make library
      - melos bootstrap

  create-tool:
    cmds:
      - mason make tool
      - melos bootstrap

  graph:
    cmds:
      - melos list --all --graph

  gviz:
    cmds:
      - dart tools/gviz_url/bin/main.dart "$(melos list --all --gviz)"
