name: styles
description: Core styles package
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  widgets:
    path: ../widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  analysis:
    path: ../analysis

flutter:
