name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  analysis:
    path: ../libraries/analysis

  home_screen:
    path: ../features/home_screen

flutter:
  uses-material-design: true
